In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [25]:
df = pd.read_csv(r'C:\Users\rashid\Desktop\analysis_project\notebook\data\raw\all_player_profiles.csv')
df.head()

   player_id                name          league position  market_value
0     804508     Viktor Gyökeres  Premier League        F    61000000.0
1     934235         Bukayo Saka  Premier League        F   126000000.0
2     794839       Gabriel Jesus  Premier League        F    21000000.0
3     922573  Gabriel Martinelli  Premier League        F    42000000.0
4     836705         Kai Havertz  Premier League        F    48000000.0

In [6]:
df.shape

(4183, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4183 entries, 0 to 4182
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   player_id     4183 non-null   int64
 1   name          4183 non-null   object
 2   league        4183 non-null   object
 3   position      4182 non-null   object
 4   market_value  4017 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 163.5+ KB

In [40]:
df.describe()

          player_id  market_value
count  4.183000e+03  4.017000e+03
mean   9.640101e+05  9.137745e+06
std    4.994639e+05  1.609177e+07
min    7.910000e+02  1.000000e+04
25%    8.062955e+05  8.600000e+05
50%    9.665420e+05  3.100000e+06
75%    1.149145e+06  1.050000e+07
max    2.522960e+06  2.180000e+08

In [26]:
df.isnull().sum()

player_id         0
name              0
league            0
position          1
market_value    166
dtype: int64

In [29]:
df[df['position'].isnull()]

      player_id                name      league position  market_value
1853    2516532  Hans-Dieter Wacker  Bundesliga      NaN           NaN

In [30]:
df[df['market_value'].isnull()]

      player_id                 name          league position  market_value
24      1842987         Khari Ranson  Premier League        G           NaN
65      1402850       Tyler Fletcher  Premier League        M           NaN
120     1462781      Kieran Morrison  Premier League        M           NaN
140     1861699  Ryan Kavuma-McQueen  Premier League        F           NaN
182     2248920           Luka Bentt  Premier League        M           NaN
...         ...                  ...             ...      ...           ...
4136    2169898        Ismaila Manga       Super Lig        M           NaN
4146    2169895         Diabel Ndoye       Super Lig        D           NaN
4168    2462525           Yaya Onogo       Super Lig        M           NaN
4181    1634332         Kerem Yandal       Super Lig        G           NaN
4182    2201957       Berke Can Evli       Super Lig        G           NaN

[166 rows x 5 columns]

In [33]:
df.duplicated().sum()

np.int64(0)

In [36]:
df['position'].value_counts()

position
M    1505
D    1341
F     817
G     519
Name: count, dtype: int64

In [37]:
df['league'].value_counts()

league
Premier League    554
Serie A           552
LaLiga            543
Bundesliga        528
Super Lig         514
Eredivisie        501
Liga Portugal     497
Ligue 1           494
Name: count, dtype: int64

In [39]:
df.groupby('league')['player_id'].count()

league
Bundesliga        528
Eredivisie        501
LaLiga            543
Liga Portugal     497
Ligue 1           494
Premier League    554
Serie A           552
Super Lig         514
Name: player_id, dtype: int64

In [43]:
df['market_value'].describe()

count    4.017000e+03
mean     9.137745e+06
std      1.609177e+07
min      1.000000e+04
25%      8.600000e+05
50%      3.100000e+06
75%      1.050000e+07
max      2.180000e+08
Name: market_value, dtype: float64

In [48]:
df.loc[df['market_value'].idxmax()]

player_id               839956
name            Erling Haaland
league          Premier League
position                     F
market_value       218000000.0
Name: 25, dtype: object

In [47]:
df.loc[df['market_value'].idxmin()]

player_id                   1157221
name            Georgiy Tunguliyadi
league                Liga Portugal
position                          D
market_value                10000.0
Name: 3523, dtype: object

In [56]:
#players whose market value is lower than 218000000 and higher than 200000000
df[(df['market_value'] < 218000000) & (df['market_value'] > 200000000)]

     player_id           name  league position  market_value
557    1402912   Lamine Yamal  LaLiga        M   215000000.0
581     826643  Kylian Mbappé  LaLiga        F   212000000.0

In [57]:
df.groupby('league')['market_value'].mean().sort_values(ascending=False)

league
Premier League    2.367419e+07
LaLiga            1.065481e+07
Serie A           9.583408e+06
Bundesliga        9.401216e+06
Ligue 1           8.508665e+06
Liga Portugal     3.787327e+06
Super Lig         2.871337e+06
Eredivisie        2.722067e+06
Name: market_value, dtype: float64

In [59]:
df.groupby('position')['market_value'].mean().sort_values(ascending=False)

position
M    1.093703e+07
F    1.085411e+07
D    8.067730e+06
G    3.707197e+06
Name: market_value, dtype: float64

In [60]:
df['market_value'].mean()

np.float64(9137744.820014937)